function arduinoMessage = readAndParseArduionoSerialMessage(s)
% this function reads a line from the serial buffer. The line has a
% predetermined format of %d%d%d%d%d%d%d%s%d with tab (\t) delimiter.
%
% Amos and Pablo
% 31-DEC-2015 :-)

 data = scanstr(s,'%d%d%d%d%d%d%d%s%d') ;
    data = textscan(data{1},'%d%d%d%d%d%d%d%s%d');
    arduinoMessage = struct('messageId',data{1},...
        'experimentElapsedTime',data{2},...
        'trialBeginningEvent',data{3},...
        'thisTrialTexture',data{4},...
        'lickEventCorrectTiming',data{5},...
        'lickEventCorrectPort',data{6},...
        'lickEventIsFirstInResponseTime',data{7},...
        'trailStage',data{8},...
        'carrouselVelocityMeterPerSec',data{9})