%summary and xcross analysis of single experiment.

%the entry poins is the structure generated by "gatherCalciumMatFiles"

path2sourceDir =  '/Users/pb/Data/PBLab/David/Testing'; %point to directory containing experiment database
compiledFileName = 'EP_FILES_COMPILED.mat'
path2resDir = [path2sourceDir filesep 'RESULTS'];

%% define analysis parameters

prmts.doComputeXcorr = 1;
prmts.doComputeSHIFT = 0;
prmts.doComputeSVD = 0;
prmts.doSubsampleImg = 1;
prmts.minCorrValToPlotEdges = 0.6;


if ~isdir(path2resDir)
    mkdir(path2resDir);
end

%% load data - data is saved as structure array
load (fullfile(path2sourceDir,compiledFileName))

%% Analysis section


nEXPERIMETS = numel(EP_FILES_COMPILED);


for iEXP = 1 : nEXPERIMETS
    
    thisEXP = EP_FILES_COMPILED(iEXP);
    
    fprintf('\nAnalyzing file %s (%d/%d)',thisEXP.dataFileName,iEXP,nEXPERIMETS)
    
    if prmts.doComputeXcorr
        fprintf('\n\t Correlation analysis started at %s',datestr(now,'hh:MM:ss'));
        thisEXP = computeXcorrAnalysis(thisEXP,prmts);
        EP_FILES_COMPILED = addNewFieldToNonScalarStruct (EP_FILES_COMPILED,thisEXP,iXP);
    end
    
    %template for adding analysis steps
    
    %if prtms.doWhateverAnalysisYouWant
    %         fprintf('\n\t whateverAnalysisName started at %s',datestr(now,'hh:MM:ss'));
    %         thisEXP = whateverAnalysis(thisEXP,prmts); %input is always
    %         'thisEXP' and the 'prmts' structure - add to it whatever
    %         needed to parametrize your analysis function
    %         The output of the analysis function is again the 'thisEXP'
    %         structure. Specific results are added as new fields.
    %
    %         %use this function to add the new results to the EP_
    %         database, the funciton takes care of making the EP_ database
    %         suitable for adding the new fields. Wiht this approach, we
    %         can add new fields and not worry about uncompatible fieldnames. 
    %   
    %         EP_FILES_COMPILED = addNewFieldToNonScalarStruct (EP_FILES_COMPILED,thisEXP,iXP);
    %end
end %cycling experimetns